### ISSUE TITLE
期望新增插件功能

### ISSUE THREAD

**Issue by longyong** [KIRA2ZERO/koishi-plugin-pool-simulator#1]
1.增加小数
例如：设置稀有度概率 碧蓝航线重巡池 超稀有:0.01% 精锐:1.99% 稀有:18% 普通:80%
2.增加保底开关按钮
例如：10连抽如果全部抽到普通就会出现9次普通1次稀有
3.增加删除或替换某个等级的物品
例如：替换物品 碧蓝航线重巡池 精锐 休斯顿 超稀有 休斯顿
           删除物品 碧蓝航线重巡池 精锐 休斯顿

**Comment by KIRA2ZERO** [comment]
已更新 @longyong
