### ISSUE TITLE
希望能增加概率小于1%的卡

### ISSUE THREAD

**Issue by s567901** [KIRA2ZERO/koishi-plugin-pool-simulator#4]
举例：
设置稀有度概率 大箱子 X级战舰或稀有战舰:0.03% VIII-IX级战舰:0.15% V-VII级战舰:0.82% 1500钢铁:1% 1500研发点:1% 15个蓝色银币加成:1.65% 15个蓝色战舰经验加成:1.65% 15个蓝色指挥官经验加成:1.65% 15个蓝色全局经验加成:1.65% 25个绿色银币加成:7% 25个绿色战舰经验加成:7% 25个绿色指挥官经验加成:7% 25个绿色全局经验加成:7% 50个信号旗:30% 1000达布隆:4% 7天高级账号:5.4% 25000全局经验:6.5% 75000指挥官经验:6.5% 7500煤炭:10%

**Comment by KIRA2ZERO** [comment]
即将更新

**Comment by s567901** [comment]
感谢！
